baseURL = "https://csabapusztai.netlify.com"
title = "Csaba Pusztai"
copyright = "Copyright © 2020, OnBased Group Kft. all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "bio"
    name = "Bio"
    url = "/about"
    weight = 12
  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 0
[[menu.main]]
    identifier = "gear"
    name = "Gear"
    url = "/gear/"
    weight = 0
[[menu.main]]
    identifier = "media"
    name = "Media"
    url = "/media/"
    weight = 0
[[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "/schedule/"
    weight = 0


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Csaba Pusztai"
  description = "This my awesome motto!"
  text = "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book."
  homepageImage = "/images/csabi.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "csabi@gmail.com"
    facebook = "https://www.facebook.com/csaba.pusztai.10"
    twitter = "https://twitter.com/csaba_pusztai"
#    linkedin = "https://linkedin.com"
#    stack-overflow = "https://stackoverflow.com"
    instagram = "https://www.instagram.com/csabi_pusztai/"
#    github = "https://github.com"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
